<a href="https://colab.research.google.com/github/SaujanShrestha/PyTorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
x = torch.rand(3,3)
print(x)

tensor([[0.7435, 0.3255, 0.1845],
        [0.9734, 0.2053, 0.1375],
        [0.9378, 0.2561, 0.9686]])


In [2]:
torch.cuda.is_available()

True

In [1]:
import torch
x = torch.rand(3,3)
print(x)

tensor([[0.5294, 0.9889, 0.3959],
        [0.9518, 0.1119, 0.0659],
        [0.2190, 0.3269, 0.0941]])


In [2]:
torch.cuda.is_available()

False

In [1]:
import torch
x = torch.rand(3,3)
print(x)

tensor([[0.2780, 0.8269, 0.7072],
        [0.5454, 0.5187, 0.3449],
        [0.5889, 0.9630, 0.8871]])


In [2]:
torch.cuda.is_available()

True

In [3]:
x = torch.empty(2,3)
print(x)

tensor([[2.6998e-40, 0.0000e+00, 5.0447e-44],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [4]:
y = torch.rand(2,3)
y

tensor([[0.1707, 0.9030, 0.8273],
        [0.3849, 0.3533, 0.9068]])

In [5]:
z = torch.zeros(1,3)
z

tensor([[0., 0., 0.]])

In [6]:
a = torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
import numpy as np
a = np.array([[1, 1, 2, 2],
                [3, 3, 4, 4]])
a.dtype

dtype('int64')

In [8]:
b = torch.tensor([[1,2],[3,4]])
#properties of tensor.
print(b.size())   #shape
print(b.dtype)    #data type
print(b.device)   #cpu or gpu

torch.Size([2, 2])
torch.int64
cpu


In [11]:
b2 = torch.tensor([[1,2],[3,4]],dtype=torch.float32)
print(b2)
print(b2.size())
print(b2.dtype)
print(b2.device)

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
torch.float32
cpu


In [12]:
print(x[:,1])

tensor([0., 0.])


In [14]:
z = torch.arange(1,10)
z = z.view(3,3)
print(z)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [15]:
if torch.cuda.is_available():
  tensor_gpu = b.to('cuda')
  print(tensor_gpu)

tensor([[1, 2],
        [3, 4]], device='cuda:0')


In [16]:
print(tensor_gpu.device)

cuda:0


In [17]:
b = torch.tensor([[1,2],[3,4]], device='cuda')
b.device

device(type='cuda', index=0)

In [19]:
x = torch.tensor([[10,20,30],
                  [40,50,60],
                  [70,80,90]])
print(x[0])
print(x[1,2])
print(x[-1])

tensor([10, 20, 30])
tensor(60)
tensor([70, 80, 90])


In [20]:
print(x[:,0])
print(x[0:2, :])
print(x[:, 1:])
print(x[::2,::2])

tensor([10, 40, 70])
tensor([[10, 20, 30],
        [40, 50, 60]])
tensor([[20, 30],
        [50, 60],
        [80, 90]])
tensor([[10, 30],
        [70, 90]])


In [22]:
#Fancy Indexing
rows = torch.tensor([0,2])
cols = torch.tensor([1,2])
print(x[rows,cols])

tensor([20, 90])


In [23]:
#Boolean Mask
mask = x > 50
print(mask)
print(x[mask])

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([60, 70, 80, 90])


In [31]:
x[0:0] = 100
x

tensor([[100,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]])

In [32]:
#Assigning values via indexing
x[0,0] = 999
print(x)

x[:,1] = torch.tensor([111,222,333])
print(x)

tensor([[999,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]])
tensor([[999, 111,  30],
        [ 40, 222,  60],
        [ 70, 333,  90]])


In [36]:
import torch, time
import numpy as np

a = np.random.rand(5000,5000)
start = time.time()
np.dot(a, a)
print("Numpy Time:", time.time() - start)

a_t = torch.rand(5000,5000, device="cuda")
torch.cuda.synchronize()
start = time.time()
torch.matmul(a_t, a_t)
torch.cuda.synchronize()
print("PyTorch GPU Time",time.time() - start)

Numpy Time: 4.215060472488403
PyTorch GPU Time 0.30068492889404297
